USE [PlayGrandmasters]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [Index_Hash]    Script Date: 21-Apr-18 10:58:26 AM ******/
CREATE UNIQUE NONCLUSTERED INDEX [Index_Hash] ON [dbo].[Games]
(
	[Hash] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO